import { AttackRangeTypes } from "@/engine/types/config";
import { ItemTypes, ItemSubTypes, WeaponSubTypes, EquipmentSubTypes, CardSubTypes, AmmoSubTypes, ShadowEquipmentSubTypes } from "@/types/equipment";
import { ItemLocations } from "@/engine/types/enums";

type typesMapType = {
    [k: string]: {
        type: ItemTypes,
        subType?: ItemSubTypes
        locations?: ItemLocations[]
    }
}
export const typesMap: typesMapType = {
        'Isca': {type: ItemTypes.Usable},
        'Roupa': {type: ItemTypes.Usable},
        'Espada': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Sword, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Espada de uma mão': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Sword, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Espada de duas mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedSword, locations: [ItemLocations.BothHands]},
        'Espada de Duas Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedSword, locations: [ItemLocations.BothHands]},
        'Adaga': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Dagger, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Katar': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Katar, locations: [ItemLocations.BothHands]},
        'Machado': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Axe, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Machado de duas mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedAxe, locations: [ItemLocations.BothHands]},
        'Machado de Duas Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedAxe, locations: [ItemLocations.BothHands]},
        'Lança': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Spear, locations: [ItemLocations.RightHand]},
        'Lança de duas mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedSpear, locations: [ItemLocations.BothHands]},
        'Lança de Uma Mão': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Spear, locations: [ItemLocations.RightHand]},
        'Lança de Duas Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedSpear, locations: [ItemLocations.BothHands]},
        'Cajado de Duas Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedStaff, locations: [ItemLocations.BothHands]},
        'Maça': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Mace, locations: [ItemLocations.RightHand]},
        'Livro': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Book, locations: [ItemLocations.RightHand]},
        'Cajado': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Staff, locations: [ItemLocations.RightHand]},
        'Arco': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Bow, locations: [ItemLocations.BothHands]},
        'Munição': {type: ItemTypes.Ammo, subType: AmmoSubTypes.Bullet},
        'Soqueira': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Knuckle, locations: [ItemLocations.RightHand]},
        'Instrumento Musical': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Instrument, locations: [ItemLocations.RightHand]},
        'Chicote': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Whip, locations: [ItemLocations.RightHand]},
        'Escudo': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Shield, locations: [ItemLocations.LeftHand]},
        'escudo': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Shield, locations: [ItemLocations.LeftHand]},
        'Equipamento para a cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equip. para Cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Armadura': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Armor, locations: [ItemLocations.Armor]},
        'Calçado': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Shoes, locations: [ItemLocations.Shoes]},
        'Calçados': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Shoes, locations: [ItemLocations.Shoes]},
        'Capa': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Garment, locations: [ItemLocations.Garment]},
        'Capuz': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Garment, locations: [ItemLocations.Garment]},
        'Acessório': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Accessory, locations: [ItemLocations.LeftAccessory,  ItemLocations.RightAccessory]},
        'Carta': {type: ItemTypes.Card, subType: CardSubTypes.Card},
        'Essência': {type: ItemTypes.Enchant},
        'Equipamento para Cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equipamento para cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Máscara': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Chapéu': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Visual': {type: ItemTypes.Costume},
        'Comida para Bicho de Estimação': {type: ItemTypes.Usable},
        'Comida para Bichinho': {type: ItemTypes.Usable},
        'Comida': {type: ItemTypes.Usable},
        'Ovo de Mascote': {type: ItemTypes.PetEgg},
        'Ovo de Bichinho': {type: ItemTypes.PetEgg},
        'Ovo de Monstro': {type: ItemTypes.PetEgg},
        'Acessório para Bicho de Estimação': {type: ItemTypes.PetEquipment},
        'Acessório de Mascote': {type: ItemTypes.PetEquipment},
        'Dagger': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Dagger, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Pistola': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Pistol, locations: [ItemLocations.BothHands]},
        'Arma': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Pistol, locations: [ItemLocations.BothHands]},
        'Revólver': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Pistol, locations: [ItemLocations.BothHands]},
        'Arma de fogo': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Pistol, locations: [ItemLocations.BothHands]},
        'Rifle': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Rifle, locations: [ItemLocations.BothHands]},
        'Espingarda' : {type: ItemTypes.Weapon, subType: WeaponSubTypes.Shotgun, locations: [ItemLocations.BothHands]},
        'Shotgun' : {type: ItemTypes.Weapon, subType: WeaponSubTypes.Shotgun, locations: [ItemLocations.BothHands]},
        'Metralhadora': {type: ItemTypes.Weapon, subType: WeaponSubTypes.MachineGun, locations: [ItemLocations.BothHands]},
        'Lança-Granadas': {type: ItemTypes.Weapon, subType: WeaponSubTypes.GrenadeLauncher, locations: [ItemLocations.BothHands]},
        'Metralhadora Gatling': {type: ItemTypes.Weapon, subType: WeaponSubTypes.MachineGun, locations: [ItemLocations.BothHands]},
        'Gatling Gun': {type: ItemTypes.Weapon, subType: WeaponSubTypes.MachineGun, locations: [ItemLocations.BothHands]},
        'Grenade Launcher': {type: ItemTypes.Weapon, subType: WeaponSubTypes.GrenadeLauncher, locations: [ItemLocations.BothHands]},
        'Projétil': {type: ItemTypes.Ammo, subType: AmmoSubTypes.Bullet},
        'Shuriken': {type: ItemTypes.Ammo, subType: AmmoSubTypes.ThrowWeapon},
        'Kunai': {type: ItemTypes.Ammo, subType: AmmoSubTypes.ThrowWeapon},
        'Shuriken Huuma': {type: ItemTypes.Weapon, subType: WeaponSubTypes.ShurikenHuuma, locations: [ItemLocations.RightHand]},
        'Huuma': {type: ItemTypes.Weapon, subType: WeaponSubTypes.ShurikenHuuma, locations: [ItemLocations.RightHand]},
        'Espada de Uma Mão': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Sword, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Sword': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Sword, locations: [ItemLocations.RightHand, ItemLocations.LeftHand]},
        'Equi. para Cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equipamento pra cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equipamento para a Cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equip. para cabeça': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Equipamento Sombrio': {type: ItemTypes.ShadowEquipment},
        'Equip. Sombrio': {type: ItemTypes.ShadowEquipment},
        'Lança-Granada': {type: ItemTypes.Weapon, subType: WeaponSubTypes.GrenadeLauncher, locations: [ItemLocations.BothHands]},
        'Acessório Direito': {type: ItemTypes.Armor, subType: EquipmentSubTypes.AccessoryRight, locations: [ItemLocations.RightAccessory]},
        'Acessório Esquerdo': {type: ItemTypes.Armor, subType: EquipmentSubTypes.AccessoryLeft, locations: [ItemLocations.LeftAccessory]},
        'Encantamento Especial': {type: ItemTypes.Enchant},
        'Acessório direito': {type: ItemTypes.Armor, subType: EquipmentSubTypes.AccessoryRight, locations: [ItemLocations.RightAccessory]},
        'Aces. Direito': {type: ItemTypes.Armor, subType: EquipmentSubTypes.AccessoryRight, locations: [ItemLocations.RightAccessory]},
        'Machado de 2 Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedAxe, locations: [ItemLocations.BothHands]},
        'Espadade Duas Mãos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedSword, locations: [ItemLocations.BothHands]},
        'Aces. Esquerdo': {type: ItemTypes.Armor, subType: EquipmentSubTypes.AccessoryLeft, locations: [ItemLocations.LeftAccessory]},
        'Calcado': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Shoes, locations: [ItemLocations.Shoes]},
        'Gun': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Pistol, locations: [ItemLocations.BothHands]},
        'Mascote': {type: ItemTypes.PetEgg},
        'Arcos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Bow, locations: [ItemLocations.BothHands]},
        'Ovo de Bichinho de Estimação': {type: ItemTypes.PetEgg},
        'Cajado de Duas Maos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedStaff, locations: [ItemLocations.BothHands]},
        'Maca': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Mace, locations: [ItemLocations.RightHand]},
        'Elmo': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
        'Vestimenta': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Armor, locations: [ItemLocations.Armor]},
        'Machado de Duas Maos': {type: ItemTypes.Weapon, subType: WeaponSubTypes.TwoHandedAxe, locations: [ItemLocations.BothHands]},
        'Machado de Uma Mão': {type: ItemTypes.Weapon, subType: WeaponSubTypes.Axe, locations: [ItemLocations.RightHand]},
        'Equipamento para Cabeça.': {type: ItemTypes.Armor, subType: EquipmentSubTypes.Headgear},
}


type nameToLocationType = {
    [t in ItemTypes]?: {
        [k: string]: {locations: ItemLocations[], subType?: ItemSubTypes};
    }
}
export const typeLocationMap: nameToLocationType = {
    [ItemTypes.Armor]: {
        "Topo": {locations: [ItemLocations.HeadUpper]},
        "Meio": {locations: [ItemLocations.HeadMid]},
        "Baixo": {locations: [ItemLocations.HeadBottom]},
        "Topo e Meio": {locations: [ItemLocations.HeadUpperMid]},
        "Topo, Meio e Baixo": {locations: [ItemLocations.HeadUpperMidBottom]},
        "Meio e Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio e baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio, Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Topo e Baixo": {locations: [ItemLocations.HeadUpperBottom]},
    },
    [ItemTypes.Costume]: {
        "Topo": {locations: [ItemLocations.HeadUpper]},
        "Meio": {locations: [ItemLocations.HeadMid]},
        "Baixo": {locations: [ItemLocations.HeadBottom]},
        "Capa": {locations: [ItemLocations.Garment]},
        "Topo e Meio": {locations: [ItemLocations.HeadUpper | ItemLocations.HeadMid]},
        "Topo e Baixo": {locations: [ItemLocations.HeadUpperBottom]},
        "Topo, Meio e Baixo": {locations: [ItemLocations.HeadUpperMidBottom]},
        "Topo, Meio e baixo": {locations: [ItemLocations.HeadUpperMidBottom]},
        "Topo,Meio e Baixo": {locations: [ItemLocations.HeadUpperMidBottom]},
        "Meio e Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio e baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio, Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Meio Baixo": {locations: [ItemLocations.HeadMidBottom]},
        "Baixo e Meio": {locations: [ItemLocations.HeadMidBottom]},
    },
    [ItemTypes.ShadowEquipment]: {
        "Malha": {locations: [ItemLocations.Armor], subType: ShadowEquipmentSubTypes.ShadowArmor},
        "Armadura": {locations: [ItemLocations.Armor], subType: ShadowEquipmentSubTypes.ShadowArmor},
        "Grevas": {locations: [ItemLocations.Shoes], subType: ShadowEquipmentSubTypes.ShadowShoes},
        "Calçado": {locations: [ItemLocations.Shoes], subType: ShadowEquipmentSubTypes.ShadowShoes},
        "Escudo": {locations: [ItemLocations.LeftHand], subType: ShadowEquipmentSubTypes.ShadowShield},
        "Brinco": {locations: [ItemLocations.RightAccessory], subType: ShadowEquipmentSubTypes.ShadowRightAcessory},
        "Brincos": {locations: [ItemLocations.RightAccessory], subType: ShadowEquipmentSubTypes.ShadowRightAcessory},
        "Aces. Direito": {locations: [ItemLocations.RightAccessory], subType: ShadowEquipmentSubTypes.ShadowRightAcessory},
        "Colar": {locations: [ItemLocations.LeftAccessory], subType: ShadowEquipmentSubTypes.ShadowLeftAccessory},
        "Aces. Esquerdo": {locations: [ItemLocations.LeftAccessory], subType: ShadowEquipmentSubTypes.ShadowLeftAccessory},
        "Luvas": {locations: [ItemLocations.RightHand], subType: ShadowEquipmentSubTypes.ShadowWeapon},
        "Luva": {locations: [ItemLocations.RightHand], subType: ShadowEquipmentSubTypes.ShadowWeapon},
        "Arma": {locations: [ItemLocations.RightHand], subType: ShadowEquipmentSubTypes.ShadowWeapon},
    }
}


type AttackRangeMap = {
    [k in WeaponSubTypes]: AttackRangeTypes;
}
export const subTypeToAttackRange: AttackRangeMap = {
    [WeaponSubTypes.Dagger]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Sword]: AttackRangeTypes.Melee,
    [WeaponSubTypes.TwoHandedSword]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Spear]: AttackRangeTypes.Melee,
    [WeaponSubTypes.TwoHandedSpear]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Axe]: AttackRangeTypes.Melee,
    [WeaponSubTypes.TwoHandedAxe]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Mace]: AttackRangeTypes.Melee,
    [WeaponSubTypes.TwoHandedMace]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Bow]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Katar]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Whip]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Instrument]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Staff]: AttackRangeTypes.Melee,
    [WeaponSubTypes.TwoHandedStaff]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Rifle]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Pistol]: AttackRangeTypes.Distance,
    [WeaponSubTypes.GrenadeLauncher]: AttackRangeTypes.Distance,
    [WeaponSubTypes.MachineGun]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Shotgun]: AttackRangeTypes.Distance,
    [WeaponSubTypes.ShurikenHuuma]: AttackRangeTypes.Distance,
    [WeaponSubTypes.Knuckle]: AttackRangeTypes.Melee,
    [WeaponSubTypes.Book]: AttackRangeTypes.Melee,
}

type CardPlacementMap = {
  [k: string]: {
    targetType: ItemTypes;
    targetSubTypes?: ItemSubTypes[];
  }
}
export const cardPlacementMap: CardPlacementMap = {
    "Arma": {targetType: ItemTypes.Weapon},
    "Armamento": {targetType: ItemTypes.Weapon},
    "Armadura": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Armor]},
    "Vestimenta": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Armor]},
    "Capa": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Garment]},
    "Calçado": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Shoes]},
    "Calçados": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Shoes]},
    "Acessório": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Accessory, EquipmentSubTypes.AccessoryLeft, EquipmentSubTypes.AccessoryRight]},
    "Equipamento para a Cabeça": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Headgear]},
    "Equipamento para a cabeça": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Headgear]},
    "Equipamento para Cabeça": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Headgear]},
    "Equipamento para cabeça": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Headgear]},
    "Equip. para Cabeça": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Headgear]},
    "Acessório Direito": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.AccessoryRight]},
    "Aces. Direito": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.AccessoryRight]},
    "Acessório Esquerdo": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.AccessoryLeft]},
    "Aces. Esquerdo": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.AccessoryLeft]},
    "Escudo": {targetType: ItemTypes.Armor, targetSubTypes: [EquipmentSubTypes.Shield]},
}
